Test delete Git tags

diff --git a/.github/workflows/delete-tags-and-releases.yml b/.github/workflows/delete-tags-and-releases.yml
--- a/.github/workflows/delete-tags-and-releases.yml
+++ b/.github/workflows/delete-tags-and-releases.yml
@@ -16,12 +16,22 @@ jobs:
 
       - name: Delete All Git Tags
         run: |
-          # List all tags and delete them
-          for tag in $(git tag --list); do
-            echo "Deleting tag $tag"
-            git push origin --delete $tag || echo "Tag $tag not found on remote"
-            git tag -d $tag || echo "Tag $tag not found locally"
+          git fetch --prune --tags
+          git tag --list | while read tag; do
+            echo "Deleting remote tag: $tag"
+            git push origin :refs/tags/$tag || echo "Failed to delete remote tag $tag"
+            echo "Deleting local tag: $tag"
+            git tag -d $tag || echo "Failed to delete local tag $tag"
           done
+      
+      # - name: Delete All Git Tags
+      #   run: |
+      #     # List all tags and delete them
+      #     for tag in $(git tag --list); do
+      #       echo "Deleting tag $tag"
+      #       git push origin --delete $tag || echo "Tag $tag not found on remote"
+      #       git tag -d $tag || echo "Tag $tag not found locally"
+      #     done
 
       - name: Delete All GitHub Releases
         env:
